server:
  port: 8080

# mysql数据库连接
spring:
  application:
    name: seckill
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 2
      max-active: 5
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-open-prepared-statements: 20
      remove-abandoned: true
      log-abandoned: true

  # redis数据库连接
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-idle: 1
        min-idle: 1
        max-active: 1
        max-wait: 0ms
    database: 0

  rabbitmq:
    ####连接地址
    host: xxxx.xxxx.xxxx.xxxx
    ####端口号
    port: 5672
    ####账号
    username: admin
    ####密码
    password: admin
    ### 地址  主机独立的virtualhost
    virtual-host: goods

mybatis:
  mapper-locations: classpath:mybatis/*.xml